### ISSUE TITLE
Ensure definition of `IsMature` (cosmos-sdk/x/staking/types/validator.go) bug free

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#111]
In `validatorUnbondingCanComplete` the following code

```go
func (k Keeper) validatorUnbondingCanComplete(ctx sdk.Context, id uint64) (found bool, err error) {
	val, found := k.GetValidatorByUnbondingId(ctx, id)
	if !found {
		return false, nil
	}


	if !val.IsMature(ctx.BlockTime(), ctx.BlockHeight()) {
		val.UnbondingOnHold = false
		k.SetValidator(ctx, val)
	} else {
		// If unbonding is mature complete it
```

https://github.com/cosmos/cosmos-sdk/blob/4cc285142ba73844e2c5929dedef59fa6db0f748/x/staking/keeper/unbonding.go#L326-L336

calls 

```go
// IsMature - is the current validator ready to unbond their coins
func (v Validator) IsMature(currentTime time.Time, currentHeight int64) bool {
	return v.UnbondingHeight < currentHeight && v.UnbondingTime.Before(currentTime)
}
```

https://github.com/cosmos/cosmos-sdk/blob/4cc285142ba73844e2c5929dedef59fa6db0f748/x/staking/types/validator.go#L180-L183

which has a different definition of maturity in `UnbondAllMatureValidators`

```go
		if keyHeight <= blockHeight && (keyTime.Before(blockTime) || keyTime.Equal(blockTime)) {
```

https://github.com/cosmos/cosmos-sdk/blob/4cc285142ba73844e2c5929dedef59fa6db0f748/x/staking/keeper/validator.go#L420

and seems suspicious.

**Comment by mpoke** [comment]
Hi @danwt. This issue was already discussed on Slack. Copying here the conversation:

There are two events of interest here:

- Event A: A validator reaches maturity on the provider chain, which results in the validator’s status  changing to `unbonded` if `UnbondingOnHold == false`. The check of maturity happens [here](https://github.com/cosmos/cosmos-sdk/blob/f133317cfe8b4723ccb5e3687ffc9ab71b52ea75/x/staking/keeper/validator.go#L424), i.e., it checks if the unbonding time or height are `<=` than the current time or height.

- Event B: A validator reaches maturity on all consumer chains, which results in either setting `UnbondingOnHold` to `false` (i.e., unlocking unbonding)  or, _**if the validator already reached maturity**_ (on the provider), changing the status to `unbonded`.

The edge case entails equality in the check for maturity in case of event B.

Event A always happens in the `EndBlock` of the Staking module.

Event B is triggered by an external module calling `UnbondingOpCanComplete()`.  Currently, this is called only by the provider CCV module when receiving the last ACK from the consumer chains; this means that currently event B is triggered during `DeliverTx` (i.e., before `EndBlock`). Thus, in case of equality, setting `UnbondingOnHold` to `false` should do the trick since the validator will be unbonded in `EndBlock()`. However, if at some point in the future some external module will call  `UnbondingOpCanComplete()` after the `EndBlock` of the staking module, then the validator will never unbond.

So, there are two options to go about it:

- Leaving the check for maturity in `UnbondingOpCanComplete()` as it is [now](https://github.com/cosmos/cosmos-sdk/blob/c36b94eb772f0ef69f1f1781b556881357387f85/x/staking/types/validator.go#L182) and add a comment clarifying this issue. May lead to potential bugs in the future. (_**This is how we decided to go about it**_)

- Change the check for maturity to include equality. This changes a bit the current behavior of Cosmos SDK. We need to make sure that between Event B (which unbonds a validator during `DeliverTx`) and Event A (which is the time when the SDK would have unbonded the validator) there are no other events that require the validator to be unbonding (e.g., `Slash`).

For the second option,

- both `Slash` and `Jail` are called in `BeginBlock`, so moving the validator to `unbonded` during `DeliverTx` has no impact on them.

- `Delegate`, `Undelegate`, and `Redelegate` seem to also not be affected, but this **_requires proper verification_**.

- `ApplyAndReturnValidatorSetUpdates()` seems to not be impacted.

**Comment by mpoke** [comment]
@danwt Do you agree?

**Comment by danwt** [comment]
Yep, it makes sense!

**Comment by mpoke** [comment]
The logic in https://github.com/cosmos/interchain-security/issues/111#issuecomment-1140917312 may be broken since `UnbondingOpCanComplete` is called also by `StopConsumerChain`

**Comment by danwt** [comment]
As of 

- https://github.com/cosmos/interchain-security/pull/188

`UnbondingCanComplete` calls are deferred to EndBlock and `provider.EndBlock` occurs always after `staking.Endblock`

**Comment by mpoke** [comment]
Issue fixed by https://github.com/cosmos/cosmos-sdk/pull/12537
