### ISSUE TITLE
Remove consumer proposal whitelist

### ISSUE THREAD

**Issue by asalzmann** [cosmos/interchain-security#1194]
### Summary

Currently, all proposals must be whitelisted on consumer chains. This is not ideal for two reasons 
1. It's hard for consumers to maintain the list of proposals
2. Providers care about what proposals are blacklisted, not what proposals are whitelisted (e.g. they want to make sure consumers don't slash them, not review the internals of the consumer code)

In practice, slashing on providers is governance gated anyway. Even if slashing weren't gated, it's unclear how much protection providers actually get from the whitelist, because software upgrades (whitelisted) and bugs can cause provider slashing.

At a minimum, I'd propose changing the whitelist on consumers to a blacklist, so consumers don't have to maintain long lists of whitelisted proposals.

It might also make sense to remove the whitelist/blacklist entirely, since it doesn't offer much protection and adds complexity.

### Problem Definition

**What problems may be addressed by introducing this change?**
- consumers can't easily maintain the whitelist
- providers can't easily review the whitelist 
**What benefits does ICS stand to gain by including this change?**
- ICS code is simpler to reason about and easier to maintain
**Are there any disadvantages of including this change?**
- changes to the whitelist might be flagged in reviewing an upgrade proposal, whereas if a blacklist is used, new props could be introduced on consumers and would be harder for reviewers to surface 

### Proposal

Remove the proposal whitelisting logic from consumers (please let me know if I should add more details here)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by strbrian** [comment]
The main disadvantage with having whitelist is that we need to take care of params in dependency modules like sdk, and ibc go, not only our own modules.
So removing the whitelisting logic would be beneficial, I think.

**Comment by mpoke** [comment]
I think it’s safe to remove it entirely. Here are the reasons:

- This is not part of the ICS library, but just in app.go. So it’s an example of how to integrate the consumer module with democracy. Consumer chains can do whatever they want (see [Stride](https://github.com/Stride-Labs/stride/blob/cb738f685b822168136962a767fd5d3b50095d3e/app/proposals_whitelisting.go#L15) for example).
- The original reason to have this mechanism was to avoid the consumer chains directly changing the CCV params. Instead, a provider-based governance solution was planned (via ICA). This work was deprioritized. As a result, consumer chains could change these params only via local governance (i.e., they need to remove the whitelisting logic).
- In a permissionless world where validators can decide whether they want to validate a consumer chain, the risk of a consumer chain changing params that might affect ICS is minimal. For example, changing the rewards distribution fraction without communicated with the validator set would result in validators opting out. 
- Finally, with the removal of unbonding operations pausing on the provider, there is no risk of a consumer chain maliciously modifying its params in order to affect liveness on the provider. The only risk is that a malicious consumer chain will fabricate SlashPackets and get the opted in validators jailed. First, the throttling mechanism mitigates the risk of halting the chain. Second, the opted in validators are responsible to make sure the consumer chain if not malicious.
