### ISSUE TITLE
Update misbehaviour handling to work with IBC 7

### ISSUE THREAD

**Issue by sainoe** [cosmos/interchain-security#1400]
## Problem
The current implementation of the cryptographic equivocation feature utilizes an IBC-Go method to validate consumer client Misbehaviour. Specifically, in IBC-Go v4, the [CheckMisbehaviourAndUpdateState](https://github.com/cosmos/ibc-go/blob/v4.4.2/modules/light-clients/07-tendermint/types/misbehaviour_handle.go#L24C23-L24C54) method confirms that a given `Misbehaviour` satisfies the following three conditions:

- The headers of the misbehaviour posses different BlockIDs for the same block height.
- The trusted state in the headers is consistent with valid consensus states.
- The commit in the headers is signed by at least the TrustLevel of their trusted validator set.

Throughout the migration from IBC-Go v6 to v7, the `ClientState` interface has undergone some changes, including the split of the `CheckMisbehaviourAndUpdateState` into four distinct methods [ref. IBC-Go doc](https://ibc.cosmos.network/v7.3.x/migrations/v6-to-v7#clientstate-interface-changes).

As a result, the upgrade of the cryptographic equivocation feature from IBC-Go v4 to IBC-Go v7 necessitates adaptation to these changes. The adjustment should ensure that the same three conditions mentioned above are enforced for handling `Misbehaviour`s.

## Closing criteria

Update the `Misbehaviour` handling to perform the same verification that in `CheckMisbehaviourAndUpdateState`.

**Comment by insumity** [comment]
What you describe sounds good to me.

The way I see this, is that [CheckMisbehaviourAndUpdateState](https://github.com/cosmos/ibc-go/blob/v4.4.2/modules/light-clients/07-tendermint/types/misbehaviour_handle.go#L24C23-L24C54) in v4.4.2 consists of the following 2 chunks:
1.  Check if  `blockID`s are different if the headers contain bogus (i.e., wrong ordering) BFT times:
```
if tmMisbehaviour.Header1.GetHeight().EQ(tmMisbehaviour.Header2.GetHeight()) {
    blockID1, err := tmtypes.BlockIDFromProto(&tmMisbehaviour.Header1.SignedHeader.Commit.BlockID)
    [...]
    blockID2, err := tmtypes.BlockIDFromProto(&tmMisbehaviour.Header2.SignedHeader.Commit.BlockID)
    [...]
    if bytes.Equal(blockID1.Hash, blockID2.Hash) {
        return ...
    }
} else {
    if tmMisbehaviour.Header1.SignedHeader.Header.Time.After(tmMisbehaviour.Header2.SignedHeader.Header.Time) {
        return ...
    }
}
```
In IBC v7.3.1, the same functionality is provided by [CheckForMisbehaviour](https://github.com/cosmos/ibc-go/blob/v7.3.1/modules/light-clients/07-tendermint/misbehaviour_handle.go#L54).

2. Compare against the trusted consensus states and verify signatures using the trusted validator set:
```
tmConsensusState1, err := GetConsensusState(clientStore, cdc, tmMisbehaviour.Header1.TrustedHeight)
[..]

tmConsensusState2, err := GetConsensusState(clientStore, cdc, tmMisbehaviour.Header2.TrustedHeight)
[...]

if err := checkMisbehaviourHeader(
    &cs, tmConsensusState1, tmMisbehaviour.Header1, ctx.BlockTime(),
); err != nil {
    return ...
}
if err := checkMisbehaviourHeader(
    &cs, tmConsensusState2, tmMisbehaviour.Header2, ctx.BlockTime(),
); err != nil {
    return ...
}
```
In IBC v7.3.1, the same functionality is provided by [VerifyClientMessage](https://github.com/cosmos/ibc-go/blob/v7.3.1/modules/light-clients/07-tendermint/update.go#L20) when called with a `Misbehaviour` message because `VerifyClientMessage` calls  [verifyMisbehaviour](https://github.com/cosmos/ibc-go/blob/main/modules/light-clients/07-tendermint/misbehaviour_handle.go#L93) that performs the above.

Therefore, we can replace IBC v4's `CheckMisbehaviourAndUpdateState` with a call to `CheckForMisbehaviour` and a call to `VerifyClientMessage` in IBC v7 as follows:
```
clientMessage := transform MsgSubmitConsumerMisbehaviour to a clientMessage with a misbehaviour
isMisbehaviour := clientState.CheckForMisbehaviour(ctx, k.cdc, clientStore, clientMessage)
err := clientstate.VerifyClientMessage(ctx, cdc, clientStore, clientMessage)
return isMisbehaviour && err != nil
```

**Comment by sainoe** [comment]
Thanks @insumity! Glad to see that we came to the same conclusion for this refactoring to IBC v7.
 The #1401 updates the `feat/ics-misbehaviour-handling` branch accordingly.
