### ISSUE TITLE
Improve unit testing (remove hacks)

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#164]
The idea is to use `TestUndelegationDuringInit` (introduced in https://github.com/cosmos/interchain-security/pull/163) as a model. The goal is to have more of an end-to-end unit testing for the scenarios covered. In general, we should avoid things such as calling the `BlockValidatorUpdates` method from the staking keeper with a modify context for triggering unbonding. 

This entails (at least) the following tasks:

- [x] replace calls to `endProviderUnbondingPeriod` and  `endConsumerUnbondingPeriod` with `incrementTimeByProviderUnbondingPeriod` and `incrementTimeByConsumerUnbondingPeriod`, respectively (see `x/ccv/provider/unbonding_test.go`)
- [ ] use the `RelayPacket` function provided by the ibc-go testing framework instead of `sendValUpdatePacket`
- [ ] use `s.providerChain.NextBlock()` instead of `s.providerChain.App.EndBlock(abci.RequestEndBlock{})`
- [ ] remove outdated UTs
- [ ] add comments describing existing UTs

**Comment by smarshall-spitzbart** [comment]
Catching this up to speed here. I'm making the assumption that the issue was originally targeted at what we now call e2e tests.

- For bullet 2, I no longer see a ```sendValUpdatePacket``` method in e2e tests, I'm guessing that bullet is complete?
- For bullet 3, I also don't see raw end block calls in e2e tests (although these are called in diff tests) Complete?
- For bullet 4, our tests are far from perfect. But I believe everything that still exists in main serves _some purpose_, even if trivial.
- Bullet 5 is an ongoing effort, but it's more completed than it was before :)

I think it'd probably make sense to close this issue. If there's anything that's glaringly unaddressed we could make separate issues

**Comment by danwt** [comment]
Yeah I think we can close this and make new issues where necessary
