### ISSUE TITLE
Partial Set Security: review the standalone to consumer changeover

### ISSUE THREAD

**Issue by sainoe** [cosmos/interchain-security#1772]
The standalone to consumer changeover process was built under some assumptions that do not hold with PSS, and therefore needs to be reviewed.

**Comment by insumity** [comment]
Looked into the changeover logic and did not find anything that could be problematic in relations to PSS and standalone to consumer changeover logic. PSS did not change anything on the consumer-module side. Therefore, PSS could not have an impact on the changeover logic (e.g., [`ChangeOverToConsumer`](https://github.com/cosmos/interchain-security/blob/30f37f7de67a03df8cab95798584646eda53a626/x/ccv/consumer/keeper/changeover.go#L30)) that exists on the consumer module. The consumer chain would use the initial validator updates created from [`MakeConsumerGenesis`](https://github.com/cosmos/interchain-security/blob/060c943b2f17b2696e668c669352a366d3610d5d/x/ccv/provider/keeper/proposal.go#L335) and whether the consumer chain is standalone or not is irrelevant.
Lastly, I modified (locally) the E2E [changeover test](https://github.com/cosmos/interchain-security/blob/060c943b2f17b2696e668c669352a366d3610d5d/tests/e2e/steps_sovereign_changeover.go#L51) using `TopN = 0` instead of `TopN = 100` in the ` SubmitConsumerAdditionProposalAction`, as well as passing a `ValidatorSetCap` to 2 and everything worked as expected.
