### ISSUE TITLE
Use protobuf to define CCV state 

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#213]
ref. https://github.com/cosmos/interchain-security/pull/188#discussion_r913138035

**Comment by MSalopek** [comment]
For more context, there seem are places where json.Marshal() is called directly because the relevant types were not created using protobuffs
- https://github.com/cosmos/interchain-security/blob/main/x/ccv/provider/keeper/keeper.go#L322
- https://github.com/cosmos/interchain-security/blob/main/x/ccv/provider/keeper/keeper.go#L427

There's some more in the same file. All examples of using json.Marshal seem to be related to managing unbonding operations.

**Comment by jtremback** [comment]
This is done, but not merged yet. Closing
