### ISSUE TITLE
[Question]: Endpoint to list consumer chains returns wrong pagination

### ISSUE THREAD

**Issue by freak12techno** [cosmos/interchain-security#2305]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

https://rest.provider-sentry-01.rs-testnet.polypore.xyz/interchain_security/ccv/provider/consumer_chains/2

Returns empty `chains`, but `pagination.total === '26'`

### Interchain Security Version

`github.com/cosmos/interchain-security/v6@v6.0.0`

### How to reproduce?

Just query the endpoint above, it's the node on a `provider` chain of ICS testnet.

**Comment by MSalopek** [comment]
Thanks for opening an issue.

I don't think this is a bug since you're not providing any pagination instructions (limit).

The system is returning the total number of entries so you are able to compare how many records are there in total.

This is the intention:
If you query without a pagination limit and your chain list is empty, you interpret it as follows: "there are 0 chains matching my query out of the total amount of chains (26)".

Notice in sdk validators that the pagination key is removed if you set the limit:
```shell
gaiad q staking validators --status BOND_STATUS_BONDED --page-limit 1 --node "https://rpc.cosmos.nodestake.top:443" -o json | jq .
{
  "validators": [
    {
      ...
    }
  ],
  "pagination": {
    "next_key": "FAd6UWZF69GY8QE0QmIbT1fNeIlg"
  }
}
➜
```

It's available if you don't set the limit:
```shell
gaiad q staking validators --status BOND_STATUS_BONDED --node "https://rpc.cosmos.nodestake.top:443" -o json | jq .
{
  "validators": [
    {...},
    {...},
  ],
  "pagination": {
    "next_key": "FIhpiwd4KhTD5FQEDQe93WgZjHgP",
    "total": "200"
  }
}
```

Do you have different needs from this query that we're currently not handling? Could you tell us more about your usecase?

**Comment by freak12techno** [comment]
Problem is that the pagination total returns the total of all consumer chains, not only consumer chains with the address I queried. For example when I query consumer chains with phase CONSUMER_PHASE_UNSPECIFIED (like this https://rest.provider-sentry-01.rs-testnet.polypore.xyz/interchain_security/ccv/provider/consumer_chains/0) it gives me `pagination.total == 28`, which is ok, as there are 28 entries in  the response. But if I query, for example, only chains that are CONSUMER_PHASE_LAUNCHED (https://rest.provider-sentry-01.rs-testnet.polypore.xyz/interchain_security/ccv/provider/consumer_chains/3), it returns currently 1 entry (which is correct), but `pagination.total` is still 28, not 1, as it I think should be (as there's only 1 chain with phase CONSUMER_PHASE_LAUNCHED, not 28).

**Comment by freak12techno** [comment]
@mpoke okay I probably fixed it, can you check the PR above?
