### ISSUE TITLE
refactor confusing function naming of Provider proposal handlers

### ISSUE THREAD

**Issue by MSalopek** [cosmos/interchain-security#365]
# Problem
Currently, the functions handling addition and removal of consumer chains proposals use confusing or misleading names.

```golang
func (k Keeper) SetPendingConsumerAdditionProp(ctx sdk.Context, clientInfo *types.ConsumerAdditionProposal) error {}

func (k Keeper) GetPendingConsumerAdditionProp(ctx sdk.Context, spawnTime time.Time, chainID string) types.ConsumerAdditionProposal {}

func (k Keeper) PendingConsumerAdditionPropIterator(ctx sdk.Context) sdk.Iterator {}

func (k Keeper) IteratePendingConsumerAdditionProps(ctx sdk.Context) {}

func (k Keeper) ConsumerAdditionPropsToExecute(ctx sdk.Context) []types.ConsumerAdditionProposal {}

```

We should discern about proposals that were accepted and executed. Those proposals should be called "Matured" Proposals, since that aligns well with the rest of the codebase.

Matured proposals have reached their spawn time and were executed upon.

# Closing criteria
Using better nomenclature, refactoring source and test files.

**Comment by smarshall-spitzbart** [comment]
`IteratePendingConsumerAdditionProps` doesn't exist anymore, I've removed it from outdated comments in https://github.com/cosmos/interchain-security/pull/370

On the other method names being confusing, I'd probably disagree. A pending proposal is one that has not been acted upon yet, and I believe the comments for the methods you've mentioned make that reasonably clear.

We don't really need to define semantics for proposals that have been executed, since the proposal is no longer persisted once acted upon. See `BeginBlockInit` and `BeginBlockCCR`
