### ISSUE TITLE
Consolidate e2e and diff-test:core 'setup' logic and bring it up to date

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#439]
# Problem

The e2e setup is here https://github.com/cosmos/interchain-security/blob/main/tests/e2e/setup.go and the diff core setup is here https://github.com/cosmos/interchain-security/blob/main/tests/difference/core/driver/setup.go. 

Both of them should be updated, and DRY should be used to factor out some commonalities.

# Closing criteria

Create new issues for subtasks or 
1. update e2e/setup (tackle in conjunction with https://github.com/cosmos/interchain-security/issues/436) to use more realistic consumer joining code
2. update difference/driver/setup to use more realistic consumer joining code
3. factor DRY style

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project 

# Detail

Both of the functionalities achieve the goal of bringing a provider and consensus chain to life, and doing the ibc handshake ect. They are slightly different, namely, the e2e/setup is more up-to-date as it uses the CreateConsumerClient and MakeConsumerGenesis provider methods. The diff setup is older, more ad-hoc and generally a mess. Also, the chain states that they use are different because the diff core chain state does things particular to the typescript model init state.

The problem is that both of these are different and complex, and neither of them really simulates the consumer joining process as it occurs in the real system flow. This means that the integration tests are catching basic things that these e2e tests cannot (I need to double check this isn't a false positive).

**Comment by danwt** [comment]
I will update or make new issues if necessary I just wanted to get this tracked.

**Comment by smarshall-spitzbart** [comment]
In order to refactor our e2e tests to use multiple consumers, we'll have to do a good amount of refactors (there's still some hacks, and the ibctesting package is flawed in some ways). This refactoring would be a great opportunity to accomplish the goals of this issue! I think some of the `testutil/simibc` tools can replace similar helpers in the `tests/e2e` directory

The prerequisite to tackling anything I've mentioned imo is to solve #498, and/or determine what version of IBC we will use for production. Upgrading IBC will change the underlying ibc testing helpers that we build upon

**Comment by danwt** [comment]
Closing as out of date but I'm still aware of problems with the setup
