### ISSUE TITLE
Create example of app.go for users, test in real configuration, fix IBC-Go test suite to handle it

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#58]
- [x] branch ibc-go and make necessary changes
- [x] fork out the ibc-go test framework and make necessary changes
  - postponed
- [x] create non-minimal example app.go for consumer
- [x] create non-minimal example app.go for provider
- [x] create minimal example app.go for consumer
  - fixed by https://github.com/cosmos/interchain-security/pull/98
- [x] create minimal example app.go for provider
  - fixed by https://github.com/cosmos/interchain-security/pull/98
- [x] make sure the apps are tested in the unit tests using ibc-go/testing
- [x] test the two apps using the docker integration tests
- [x] add comment in app.go addressing the order of `EndBlock` (see https://github.com/cosmos/interchain-security/issues/51#issuecomment-1125143988)
  - moved to https://github.com/cosmos/interchain-security/pull/98

**Comment by jtremback** [comment]
In the short term, there will be 3 different users of our `app.go` example. 

- First, the Cosmos Hub team at IG will need to install the CCV provider module into the Cosmos Hub's `app.go`.
- Then the Ethernal team will need to install the CCV consumer module into the CosmWasm consumer chain. 
- Also, teams with custom consumer chains will need to install the CCV consumer module as well.

I think it will be important have separate app.go files for provider and consumer chains. This is because the functioning of the consumer chain depends on certain modules being disabled. Even if we fixed this somehow, we would still want separate `app.go`s because the Hub will not want to pull in the consumer module and increase the attack surface.

For this to happen some changes will need to be made to the IBC-Go test suite to allow it to test two chains with separate `app.go`s.

As I just discussed with @danwt I think the time has come for us to fork the IBC-Go test framework into it's own repo. Dealing with a test framework that needs frequent modifications but also is bundled with one of our core dependencies is a pain.

**Comment by danwt** [comment]
> fork the IBC-Go test framework into it's own repo.

I think it's a good idea. The ultimate goal would be to have a general tool for testing ibc apps across heterogeneous chains so the name could be something like 'ibc-tester'. It must be built for our needs first though, without premature generalization.

**Comment by danwt** [comment]
- [ ] fork ibc-go test framework and make necessary changes
- [ ] create example app.go for consumer
- [ ] create example app.go for provider
- [ ] test the two chains in a real configuration using the improved ibc-go testing

**Comment by danwt** [comment]
This issue is relevant for understanding current ibc-go testing limitations

- https://github.com/cosmos/ibc-go/issues/918

**Comment by danwt** [comment]
From speaking with @jtremback we decided this has high priority. I will tackle this first.

**Comment by danwt** [comment]
This issue is quite related to 
- https://github.com/cosmos/interchain-security/issues/77

**Comment by danwt** [comment]
Two PRs solve the basics of this issue

- https://github.com/informalsystems/ibc-go/pull/1 - enables multiple app.go's in testing framework
- https://github.com/cosmos/interchain-security/pull/84 - uses multiple app.go's in interchain security

Now there are two copies of the app.go that contains both provider and consumer logic so I should additionally strip the provider-only logic from the consumer and the consumer-only logic from the provider. That might fall better under either of

- https://github.com/cosmos/interchain-security/issues/59
- https://github.com/cosmos/interchain-security/issues/77

Additionally I need to make sure the docker integration tests work with the new apps

**Comment by danwt** [comment]
Hi @alexanderbez. We spoke on slack. Here's my understanding

The ultimate goal is to have two separate app's that people can use as a basis. The provider can be like gaia and the consumer should be minimal but with [democracy and/or cosmwasm](https://github.com/cosmos/interchain-security/issues/77#issuecomment-1118675955). As I understand democracy is needed to enable cosmwasm in practice. Ethernal are working on cosmwasm and they are having problems with conflicting sdk versions ect. There is some uncertainty about the best way to structure the repo(s) to make all this possible.

The PR https://github.com/cosmos/interchain-security/pull/84 doesn't do much. It simply splits the apps and updates the tests (in-memory and integration) to use two different apps.

**Comment by danwt** [comment]
Can we close this?
