### ISSUE TITLE
Figure out IBC version situation

### ISSUE THREAD

**Issue by jtremback** [cosmos/interchain-security#585]
Either:

1. Get the IBC-Go team to upstream our changes to IBC

2. Or use some dependency ninja techniques to test with with informal/ibc and then compile for production with cosmos/ibc. This is safe as long as our changes only modify ibc-go test framework.
  a. We need to verify that our changes do not modify the core

3. Take out all the testing stuff from ibc-go and use it as a separate testing framework, while using the real ibc-go for the actual code

**Comment by jtremback** [comment]
@glnro Was there anything left to do on this? I think we can go with option 2, right?

**Comment by glnro** [comment]
Yes, 2 is the most viable path in the short to near term. In a worst case, Gaia uses mainline IBC and the provider test targets a commit of Gaia using informal/ibc to implement a test method on GaiaApp

**Comment by glnro** [comment]
Summarizing the last discussion, there are currently two different outsanding issues that persist:
1. ICS is still using Informal's IBC fork instead of the official ibc-go version 3.4.0
2. There is a method that[ GaiaApp must implement that returns an staking keeper interface](https://github.com/cosmos/gaia/pull/1938/commits/f73f97517b5beeb60aa6a639f2dc55448f86bd69#diff-1ac782d2fab1d48ad7f7ef06cf2d58b37c99b6b4c98879a5ad86a985b73fad58R408) that is not compatible with ibc-go v3.4.0 and relies on the informal fork. This method is [only used for e2e testing IN the ICS repo](https://github.com/cosmos/interchain-security/blob/main/tests/e2e/instance_test.go#L60). Per @crodriguezvega, this is something that was backported to ibc v5, but cannot be backported to v3.

The Gaia specific ICS tests are not necessary for the purpose of cutting a release of Gaia with ICS. However it is crucial that ICS and Gaia are using the same official release version of IBC. To address issue 1 for release, @sainoe and @smarshall-spitzbart will work on pulling out observability methods from the fork's ibc core for testing, as well as pasting in relevant ibc testing changes into a local package per @crodriguezvega's suggestion ([cosmwasm example](https://github.com/CosmWasm/wasmd/tree/main/x/wasm/ibctesting)). Once this version of ICS is ready, it can be integrated in Gaia. Then a further discussion can be had on how to best address issue 2 in the short and medium-long term.

**Comment by okwme** [comment]
gaia has `GetStakingKeeper` but it's been commented out and tracked in #1909.
https://github.com/cosmos/gaia/blob/main/app/keepers/keepers.go#L373

Seems like moving the ibctesting into its own module so it could be used across versions would be clean but maybe not possible?

**Comment by mpoke** [comment]
Fixed by https://github.com/cosmos/interchain-security/pull/632
