### ISSUE TITLE
Double sign slashing

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#65]
Implement Consumer Initiated Slashing for double-signing evidence (see [spec](https://github.com/cosmos/ibc/blob/marius/ccv/spec/app/ics-028-cross-chain-validation/technical_specification.md#consumer-initiated-slashing)).

**Comment by zmanian** [comment]
Has a decision been made that double sign slashing evidence will be initiated by the consumer chain and evaluated by the consumer's tendermint instance?

The alternative design would be to extend the IBC client misbehavior handling mechanism to enable handling proposal, prevote and precommit misbehavior so that evidence is evaluated on the provider chain
