### ISSUE TITLE
A potential misuse of throttling mechanism against a consumer

### ISSUE THREAD

**Issue by ivan-gavran** [cosmos/interchain-security#685]
Let there be a group of validators who want to harm a consumer `C`.
Consider the following attack, taking advantage of the throttling mechanism:
1. Validators commit infractions on `C` (and get slashed and jailed in the process).
2. In that way, they are stalling the [per-chain queue](https://github.com/cosmos/interchain-security/blob/463ec20c87423897009bd78c2dbf96d28bd8f150/docs/throttle.md?plain=1#L25) of the consumer and eventually manage to kick it out from the list of consumers by sufficiently delaying processing of its `MatureVSC` messages.

This is a "draft issue". As discussed with @smarshall-spitzbart , we need to figure out whether the attack is realistic. Requirements are:
 - overall power of malicious validators is < 50% (or otherwise they could've just vote against the consumer)
 - jailing does not stop validators from performing their attack
 - slashing does not make the attack overly expensive

**Comment by smarshall-spitzbart** [comment]
Here's my thoughts on this issue, lmk if my logic is flawed anywhere:

If a majority of provider validators do not like a consumer chain, it'd be way less effort to start a governance proposal to remove that consumer. 

In the event of a slash attack you've described, the malicious validators are in the initial active set, and want the attack to take as long as possible, as opposed to the main slash attack we've discussed, where the malicious validators are below the initial active set and want the attack to be as quick as possible.

The default consumer unbonding period is 2 weeks and 6 days. The default VSC timeout period is 5 weeks. Meaning the attack would need to throttle all VSC matured packets from a consumer for a little over 2 weeks. This attack seems very costly, and hard to achieve. However, I haven't even thought about invariants for the maximum time that a throttle attack could take, only a minimum. 

Considering this, I'll do some napkin math to analyze the longest time these attackers could throttle all VSC matured packets (ie. keep the per chain queue non-empty). Lets assume 66% of provider validators have colluded to commit the attack on a consumer (anymore than a 66% attack and the attackers might as well commit arbitrary state on the provider). Lets assume there are no validators below the active set at the start of the attack (worst case scenario). The attack starts when total voting power is 1000. At the end of a failed attack, there would only be the 33% honest validators left in the active set, with a total voting power of 333, since the attackers are disincentivized to unjail themselves. That is, unjailing makes the throttle queues empty out quicker, since total voting power would be higher.

Using default throttling params, we allow 5% of total voting power to be jailed/tombstoned per 1 hour. Total voting power during the attack would start at 1000 and decrease to 333. Lets use a constant value that would represent the power that makes the queues take the longest to empty out. This value is 333. 

Worst case allowance is: `5% * 333 total voting power` ~= 16 voting power. So the worst case period of time that the malicious 66% of validators could clog a per-chain queue is: `maliciousVotingPower / allowancePerHour` = `666 / 16` = 41.6 hours = 1.73 days

1.73 days is significantly less than than the difference betwen the default VSC timeout period and the default consumer unbonding period. Therefore, I don't think this attack is a plausible. However, if parameters are set incorrectly, the attack could be possible.

Maybe it's worth adding this time dependance to `params.md`?

**Comment by smarshall-spitzbart** [comment]
Now, if I take the same scenario described and say that ~100% of provider validators collude to attack the consumer, the worst case allowance approaches 0, and the period of time that the validators could clog the per-chain queue approaches infinity, making this a plausible attack. This is an interesting theoretical to think about, but obviously not something we need to guard against 😆

**Comment by smarshall-spitzbart** [comment]
Awesome, I can take a look at your comment but the link currently doesn't work for me

**Comment by ivan-gavran** [comment]
Ah, internal repo, and I cannot make you a member. Nevermind, pasting the comment here:


The [global entry queue](https://github.com/cosmos/interchain-security/blob/463ec20c87423897009bd78c2dbf96d28bd8f150/docs/throttle.md?plain=1#L21) consists of sequences of slashing requests  $(S_1, S_2,...)$. Per-chain queues additionally include maturity notifications.
Since maturity notifications do not influence processing time at all (any maturity-prefix of the queue [is processed immediately](https://github.com/cosmos/interchain-security/blob/463ec20c87423897009bd78c2dbf96d28bd8f150/x/ccv/provider/keeper/relay.go#L280-L280)), we can think of the queue being exactly $(S_1, S_2, \ldots, S_n, M)$, where $M$ is the maturity notification whose delay interests us. (In the real system, $M$ is a part of a per-chain queue and won't be processes until the $S_n$,  a slash request of the same chain, is processed.)

Let $t(M)$ be the time needed to process maturity notification $M$.
(If there were no throttling, that would happen as a part of the same block, and we would consider that to be $t(M) = 0$.)

At block $b$, with the full meter, we can process requests $S_1, ..., S_j$ which satisfy the inequality $S_1 + \ldots + S_{j-1} < f \cdot \mathit{totalPower(b)}$, where:
 - $f$ is the [`SlashMeterReplenishFraction`](https://github.com/cosmos/interchain-security/blob/463ec20c87423897009bd78c2dbf96d28bd8f150/x/ccv/provider/types/provider.pb.go#L281-L281)
 - $\mathit{totalPower(b)}$ is the total power of validators at block $b$, as obtained by the function [`GetLastTotalPower`](https://github.com/cosmos/interchain-security/blob/463ec20c87423897009bd78c2dbf96d28bd8f150/x/ccv/types/expected_keepers.go#L36-L36)

We note here that there is some freedom with respect to the value of the $S_j$ request.
However, in the long run, this is averaged out since the meter can go negative and will take time proportional to the value of $S_j$ to get back to the positive state. 

Let $T_{\mathit{min}}$ be a minimum total power of the chain over all blocks in which the sequence $S_1,\ldots, S_n$ is processed. 

 Then, whenever the meter is full, we can process at least $S_1, ..., S_j$ which satisfy the inequality $S_1 + \ldots + S_{j-1} < f \cdot T_{\mathit{min}}$.
Thus, the overall time needed to process maturity request $M$ is
```math
t(M) \leq \frac{\sum_{i = 1 .. n} S_i}{f \cdot T_{\mathit{min}}} \cdot p
```
where $p$ is [`SlashMeterReplenishPeriod`](https://github.com/cosmos/interchain-security/blob/463ec20c87423897009bd78c2dbf96d28bd8f150/x/ccv/provider/types/provider.pb.go#L278-L278)

With current default values of $f = 0.05$ and $p = 1$, we will process $M$ after no more than $20 \cdot \frac{\sum_{i = 1 .. n} S_i}{T_{\mathit{min}}}$ hours.

**Comment by smarshall-spitzbart** [comment]
@ivan-gavran this analysis looks good to me, and is awesome to see, thanks!
