### ISSUE TITLE
Should we check ChannelToChain on AcknowledgePacket

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/interchain-security#716]
ChannelToChain mapping is checked on TimeoutPacket but not on AcknowledgePacket

https://github.com/cosmos/interchain-security/blob/463ec20c87423897009bd78c2dbf96d28bd8f150/x/ccv/provider/keeper/relay.go#L141
https://github.com/cosmos/interchain-security/blob/463ec20c87423897009bd78c2dbf96d28bd8f150/x/ccv/provider/keeper/relay.go#L120

Not sure if there is a reason for the difference

**Comment by insumity** [comment]
Synced (offline) with @AdityaSripal and we can close this ticket.

The reason being that `k.GetChannelToChain` is actually called by both `OnTimeoutPacket` and `OnAcknowledgementPacket`. Note that `k.GetChannelToChain` is used in a similar fashion by both methods. In `OnTimeoutPacket` we know something went wrong due to the timeout and we get the chain with  `k.GetChannelToChain`, if we find the chain we [stop it](https://github.com/cosmos/interchain-security/blob/463ec20c87423897009bd78c2dbf96d28bd8f150/x/ccv/provider/keeper/relay.go#L152). Similarly, in `OnAcknowledgementPacket` if there's an error in the acknowledgement, we get the chain through `k.GetChannelToChain` and if we find the chain we [stop it](https://github.com/cosmos/interchain-security/blob/463ec20c87423897009bd78c2dbf96d28bd8f150/x/ccv/provider/keeper/relay.go#L131).
