### ISSUE TITLE
Validate upgrade related app.go code for sovereign -> consumer changeover

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#783]
To resolve this issue, please take a look at the changes in #757 regarding `app/consumer-democracy/app.go` 

Questions to answer:
- upgradeName used [here](https://github.com/cosmos/interchain-security/blob/4b5fd84513501b3d4e1d7223ad0b4ac57b548728/app/consumer-democracy/app.go#L631) links to `"v07-Theta"`. Is this okay?
- This [newly introduced code](https://github.com/cosmos/interchain-security/blob/4b5fd84513501b3d4e1d7223ad0b4ac57b548728/app/consumer-democracy/app.go#L642) is added to the upgrade handler. Should that code be there for both a newly created democracy consumer, and a democracy consumer that was previously a sovereign chain? Or should we add some sort of if-statement 
- Same thing [here](https://github.com/cosmos/interchain-security/blob/4b5fd84513501b3d4e1d7223ad0b4ac57b548728/app/consumer-democracy/app.go#L674). Should the ccv consumer module be "added" for both a normal democracy consumer, and a democracy consumer that was previously sovereign?

**Comment by dusan-maksimovic** [comment]
Since Shawn asked us if we can take a look at this, we are writing our answers here:

The consumer-democracy/app.go (just like consumer/app.go) is an example application for clients to know how to build app.go for their chains. This app was also used for testing purposes and was always staring from height 0, so it never needed any of these things regarding upgrade handler. As for the sovereign chains, since they were already running, they must write these upgrade handlers which are always application specific, which means they need to write them in their app.go. So, adding this upgrade-related code to the consumer-democracy/app.go will not have any purpose, except if you want to show to other clients how they should write upgrade handlers in their chain's app.go file.

Answers to your questions:
1. Upgrade names are application specific, usually the name of version the chain is upgrading to. This name "v07-Theta" was c/p from gaia app.go and has been there since the file was created. Consumer chain will set the upgrade name that they choose.
2. As I mentioned above, for new chain this code (together with entire SetUpgradeHandler()) is not needed at all. It is application specific, so sovereign consumer chains should write upgrade handler in their code. However, if you want to show them an example of how this should be done, you can keep this code together with the entire SetUpgradeHandler(). Bare in mind that this code is just an example for upgrading the consumer-related stuff, but specific chains can include some other upgrades needed by their chain as well.
3. This is needed for sovereign chains that are migrating to new version with consumer module. Again, if you want to have an example how it's done then you can leave it here, but they will have to add it to their app.go as well.

**Comment by smarshall-spitzbart** [comment]
Much appreciated @dusan-maksimovic! Comments have been added in https://github.com/cosmos/interchain-security/commit/aa6da31262e04163c0883c2066a0052bd5379d0d resolving this issue
