### ISSUE TITLE
Test edge cases with clients expiring 

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#95]
In the case one of the chains is offline for a while, its client on the counterparty could be frozen. The client could be recovered through governance, but not sure what will happen with the channel since most likely all outstanding packets will timeout, which will cause the channel to close.

**Comment by mpoke** [comment]
We need to test the following scenarios:

- [ ] the provider chain is offline for more than unbonding period
- [ ] the consumer chain is offline for more than unbonding period

For both scenarios, we need to enable the recovery of the CCV channel between the two chains.

**Comment by mpoke** [comment]
@AdityaSripal Is there anything else we should be aware of here?

**Comment by mpoke** [comment]
Related to https://github.com/cosmos/interchain-security/issues/121

**Comment by jtremback** [comment]
Don't we just remove the consumer chain if it times out? That's intentional, right?

If the provider chain times out long enough that all of its clients on each consumer chain time out, this seems like an interesting edge case. Currently, I imagine what will happen is that no more packets can be sent between the provider and consumers, which will lead to the consumer clients timing out after the provider comes back online. This doesn't seem like an entirely illogical outcome, and this whole scenario is quite a niche edge case. Also, it may be possible to fix this through governance proposals, and definitely possible to fix it with chain upgrades. Should this issue be closed?
