### ISSUE TITLE
Add a command to Gaia to retrieve all consumer chain keys for a specific consumer chain

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/interchain-security#984]
## Summary

Add a command for getting all consumer keys for a consumer chain.

## Problem Definition

I want to be able to add a consumer chain support for my monitoring bot, and I’ll need to query for consumer keys on all validators, and it’s more correct to query all of it at once with one query instead of querying it for each validator separately

## Proposal

See originating linked issue in Gaia: https://github.com/cosmos/gaia/issues/2555
See detailed comment by @freak12techno, https://github.com/cosmos/gaia/issues/2555#issuecomment-1568061608

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by freak12techno** [comment]
I'd love to work on it, feel free to assign me to it.
I'd need some assistance though: `make proto-all` doesn't work for me, I reported it as a separate issue: https://github.com/cosmos/interchain-security/issues/993

**Comment by mpoke** [comment]
@freak12techno I assigned this issue to you. Thanks for deciding to contribute on Interchain Security. 

We'll look into https://github.com/cosmos/interchain-security/issues/993 and get back to you.

**Comment by freak12techno** [comment]
@mpoke okay I did most of the code but I am unsure of how to test it.
Is there a guide or a script or something about setting up a provider + consumer chain locally? Currently I am having this issue, not sure where to follow:

```
Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain
```

This one happens after I craft the genesis on a provider chain and then run it.

If there'd be a page for new developers on how to craft provider genesis/craft consumer genesis/run both of them/add a consumer chain to provider chain via proposal/running all of them + relaying packets between chains, or a script to bootstrap all of it instead of doing it manually, or both, that'd be really nice, as it can be hard for new developers to onboard.

(If you are the wrong person to ask this, feel free to ping those who are able to answer, not sure about who to ping here)

**Comment by mmulji-ic** [comment]
Hi @freak12techno we have some resources, will dig them up and reference them here.

**Comment by keupsonite** [comment]
+1

**Comment by mmulji-ic** [comment]
Hey @keupsonite @freak12techno checking ...

**Comment by mmulji-ic** [comment]
Following up from Discord: Hi @freak12techno , if you want to setup a testnet you can try Hyphas setup: 
https://github.com/hyphacoop/cosmos-ansible/blob/main/local-rs-testnet.yml, alternately you can join the testnet as is with your modified Gaia.

**Comment by mpoke** [comment]
Closing as fixed by https://github.com/cosmos/interchain-security/pull/1503
